### ISSUE TITLE
Add InfinityWard Detection

### ISSUE THREAD

**Issue by diedyesterdaywashere** [SteamDatabase/FileDetectionRuleSets#182] opened 2023-01-27 22:44 UTC
### Some reference to the engine, such as the developer site or a wikipedia article.

https://en.wikipedia.org/wiki/IW_(game_engine)
This engine probably has multiple iterations like idTech so files may differ

### SteamDB links

https://steamdb.info/app/10080/
https://steamdb.info/app/2630/
https://steamdb.info/app/7940/
https://steamdb.info/app/42700/
https://steamdb.info/app/202970/
https://steamdb.info/app/311210/
https://steamdb.info/app/209160/
https://steamdb.info/app/292730/
https://steamdb.info/app/10180/
https://steamdb.info/app/115300/
https://steamdb.info/app/1938090/
https://steamdb.info/app/1962663/
https://steamdb.info/app/10090/

**Comment by Lifeismana** [comment] 2023-02-01 22:48
duplicate of #92

**Closed by Lifeismana** 2023-02-01 22:48 UTC
Labels: Type: Engine
