### ISSUE TITLE
Evochron Mercenary

### ISSUE THREAD

**Issue by dukemagus** [SteamDatabase/FileDetectionRuleSets#68] opened 2021-08-13 19:00 UTC
### SteamDB link to the game

https://steamdb.info/app/71000/

### What is it being detected as and what should it be detected as? Any other information?

It's being detected as a godot game. So far i haven't found anything hinting to that. 
Also, the game was released in 2012 and godot's source code was released in 2014.

As a rule of thumb, any game from before 2014 wasn't made with godot unless it was made released by godot's developers (ir wasn't commercialized back then)

**Comment by xPaw** [comment] 2021-08-13 19:02
Duplicate of #30

**Closed by xPaw** 2021-08-13 19:02 UTC
Labels: False positive
