### ISSUE TITLE
Borderlands 2 wrongly detected as XNA

### ISSUE THREAD

**Issue by LaserYGD** [SteamDatabase/FileDetectionRuleSets#79] opened 2021-08-18 14:03 UTC
### SteamDB link to the game

https://steamdb.info/app/49520/

### What is it being detected as and what should it be detected as? Any other information?

Borderlands 2 is being wrongly detected as XNA. It should be detected as Unreal Engine.

**Comment by xPaw** [comment] 2021-08-18 14:08
It does have Microsoft.Xna.Framework.dll in there.

@larsiusprime XNA is more of an SDK, don't you think?

**Comment by Narann** [comment] 2021-09-03 09:02
I think that if both XNA and Unreal are detected, Unreal should have precedence (same for Unity or any dedicated game engine).

My 2cts.

**Comment by larsiusprime** [comment] 2021-09-03 13:32
@xPaw: So, XNA is at least as much of an engine as a lot of other things on our list. That's definitely how the community thinks of it.

My guess here is that Borderlands is one of those cases where there's a launcher or something packed into one of the depots that was written using XNA, and so it's legitimately being picked up, but it confuses people because they don't think of that as the main engine.

Creating some kind of precedence rule can fix edge cases like this, but it's not uncommon to see Unity packed in as a launcher with some other engine, so giving Unreal/Unity precedence over "smaller" stuff like XNA will not necessarily lead to more accurate results across the board.

**Comment by xPaw** [comment] 2021-09-03 13:33
So close this as working as intended?

**Comment by larsiusprime** [comment] 2021-09-03 13:35
If you're okay with the philosophy I described above I guess so. 
The problem is it legitimately confuses people, so there might need to be an extra sentence added to our notes about how detection works. But I don't see how we could fix this uniformly in a system that relies on heuristics alone.

**Comment by xPaw** [comment] 2021-09-03 13:36
Well we already agreed that multiple detections in a single game are OK, and this is the case here.

**Comment by larsiusprime** [comment] 2021-09-03 13:38
Alrighty. Then we're agreed we can't solve this in SteamDB. If people want to maintain manual correction lists outside of this system to deal with these edge cases that's up to them.

**Closed** 2021-09-03 13:38 UTC
Labels: False positive
